env:
  es2020: true
  node: true
extends:
  - eslint:recommended
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
overrides:
  - files: "src/**/*.ts"
    extends:
      - prettier/@typescript-eslint
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:import/typescript
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      sourceType: module
    rules:
      "@typescript-eslint/explicit-module-boundary-types": off
      "@typescript-eslint/no-var-requires": off
plugins:
  - import
  - sort-keys-fix
rules:
  import/no-extraneous-dependencies: error
  import/order:
    - error
    - alphabetize:
        order: asc
  sort-keys-fix/sort-keys-fix: error
settings:
  import/core-modules:
    - atom
