env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  atom: false
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
