env:
  es6: true
  node: true
extends:
  - prettier
  - prettier/@typescript-eslint
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/warnings
overrides:
  - files: "src/**/*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      sourceType: module
plugins:
  - "@typescript-eslint"
  - sort-keys-fix
rules:
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type": error
  "@typescript-eslint/ban-types": error
  "@typescript-eslint/class-name-casing": error
  "@typescript-eslint/consistent-type-assertions": error
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/indent": off
  "@typescript-eslint/member-delimiter-style":
    - off
    - multiline:
        delimiter: none
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
  "@typescript-eslint/member-ordering": error
  "@typescript-eslint/no-empty-function": error
  "@typescript-eslint/no-empty-interface": error
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/no-unnecessary-type-assertion": off
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-namespace-keyword": error
  "@typescript-eslint/quotes": off
  "@typescript-eslint/require-await": off
  "@typescript-eslint/semi": off
  "@typescript-eslint/triple-slash-reference": error
  "@typescript-eslint/type-annotation-spacing": off
  "@typescript-eslint/unified-signatures": error
  arrow-parens: error
  camelcase: error
  comma-dangle: off
  complexity: off
  constructor-super: error
  dot-notation: error
  eol-last: off
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  id-blacklist: error
  id-match: error
  import/no-unresolved: off
  import/order:
    - error
    - alphabetize:
        order: asc
  linebreak-style: off
  max-classes-per-file: off
  max-len: off
  new-parens: off
  newline-per-chained-call: off
  no-bitwise: off
  no-caller: error
  no-cond-assign: error
  no-console: off
  no-debugger: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-eval: error
  no-extra-semi: off
  no-fallthrough: off
  no-invalid-this: off
  no-irregular-whitespace: off
  no-multiple-empty-lines: off
  no-new-wrappers: error
  no-shadow:
    - error
    - hoist: all
  no-throw-literal: error
  no-trailing-spaces: off
  no-undef-init: error
  no-underscore-dangle: error
  no-unsafe-finally: error
  no-unused-labels: error
  no-var: error
  object-shorthand: error
  one-var:
    - error
    - never
  prefer-const: error
  quote-props:
    - error
    - as-needed
  radix: error
  sort-keys-fix/sort-keys-fix: error
  space-before-function-paren: off
  space-in-parens:
    - off
    - never
  spaced-comment: error
  use-isnan: error
  valid-typeof: off
